version: '3'
services:
  redis:
    image: "${REDIS_IMAGE}"
    container_name: redis-server
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always